[workspace]
members = [
  "motor_core",
  "motor_vendors/damiao",
  "motor_vendors/robstride",
  "motor_vendors/robstride_cia402",
  "motor_vendors/robstride_mit",
  "motor_vendors/myactuator",
  "motor_vendors/hexfellow",
  "motor_vendors/hightorque",
  "motor_vendors/template",
  "motor_cli",
  "motor_abi",
  "integrations/ws_gateway",
]
resolver = "2"

[workspace.package]
version = "0.5.3"
edition = "2021"
authors = ["tianrking"]
license = "MIT"
repository = "https://github.com/motorbridge/motorbridge.git"
homepage = "https://github.com/motorbridge/motorbridge"
description = "Unified CAN motor control stack with pluggable vendor drivers and C ABI"

[workspace.lints.clippy]
all = "warn"
