"""t2 -- IK roundtrip: for each task mode, >=5 REACHABLE poses generated by FK
(so a solution is guaranteed to exist), then IK -> FK must reproduce the task:

    position error   < 1e-6 m
    orientation error< 1e-5 rad   (full rotation for pose_6d, tool-axis angle
                                   for approach_5d, trivially 0 for position_3d)
    joint-limit violations = 0 (all returned q strictly inside URDF limits)
    task nullity at non-singular solutions: position_3d=3, approach_5d=1, pose_6d=0
"""
import _helpers
import numpy as np

import ik

POS_TOL = 1e-6
ORI_TOL = 1e-5
EXPECT_NULLITY = {"pose_6d": 0, "approach_5d": 1, "position_3d": 3}
N_POSES = 5
GEN_SEED = 20260712          # deterministic FK pose generation


def _gen_pose(arm, rng, lo, hi):
    """Random q inside the limits, rejected (deterministically) if the full
    geometric Jacobian is badly conditioned (near-singular pose)."""
    while True:
        q = rng.uniform(lo + 0.15, hi - 0.15)
        f = arm.fk(q)
        sv = np.linalg.svd(arm.jacobian(q, fk_out=f), compute_uv=False)
        if sv[0] / sv[-1] < 200.0:
            return q, f


def run():
    arm = ik.get_arm()
    lo, hi = ik.joint_limits(arm)
    rng = np.random.default_rng(GEN_SEED)
    worst = 0.0
    per_mode = {}
    for mode in ("pose_6d", "approach_5d", "position_3d"):
        wp = wo = 0.0
        nullities = set()
        n_limit_viol = 0
        for _ in range(N_POSES):
            q_true, f = _gen_pose(arm, rng, lo, hi)
            p_des = f["T_E"][:3, 3]
            if mode == "pose_6d":
                task = ik.make_task(mode, p_des, R_des=f["T_E"][:3, :3])
            elif mode == "approach_5d":
                task = ik.make_task(mode, p_des, a_des=f["T_E"][:3, 2])
            else:
                task = ik.make_task(mode, p_des)
            sols = ik.solve_ik(task, np.zeros(6))
            assert sols, f"{mode}: no IK solution for FK-generated pose q={q_true}"
            for s in sols:
                q = np.asarray(s["q"])
                if np.any(q < lo) or np.any(q > hi):
                    n_limit_viol += 1
                if s["condition_number"] < 1e3:      # non-singular solutions only
                    nullities.add(s["task_nullity"])
            # roundtrip error of the SELECTED solution, via a fresh FK
            fs = arm.fk(np.asarray(sols[0]["q"]))
            wp = max(wp, float(np.linalg.norm(fs["T_E"][:3, 3] - p_des)))
            if mode == "pose_6d":
                Rerr = f["T_E"][:3, :3] @ fs["T_E"][:3, :3].T
                ang = np.arccos(np.clip((np.trace(Rerr) - 1.0) / 2.0, -1.0, 1.0))
                wo = max(wo, float(ang))
            elif mode == "approach_5d":
                ca = np.clip(fs["T_E"][:3, 2] @ f["T_E"][:3, 2], -1.0, 1.0)
                wo = max(wo, float(np.arccos(ca)))
        assert wp < POS_TOL, f"{mode}: position roundtrip {wp:.2e} >= {POS_TOL}"
        assert wo < ORI_TOL, f"{mode}: orientation roundtrip {wo:.2e} >= {ORI_TOL}"
        assert n_limit_viol == 0, f"{mode}: {n_limit_viol} joint-limit violations"
        assert nullities == {EXPECT_NULLITY[mode]}, \
            f"{mode}: nullities {nullities}, expected {{{EXPECT_NULLITY[mode]}}}"
        per_mode[mode] = {"worst_pos_m": wp, "worst_ori_rad": wo,
                          "nullity": sorted(nullities), "limit_violations": 0}
        worst = max(worst, wp, wo)
    return {"name": "t2_ik_roundtrip", "passed": True, "worst_residual": worst,
            "per_mode": per_mode,
            "note": f"{N_POSES} FK-generated poses per mode, tol {POS_TOL} m / {ORI_TOL} rad"}


if __name__ == "__main__":
    out = run()
    for m, d in out["per_mode"].items():
        print(f"{m:12s} pos {d['worst_pos_m']:.2e} m  ori {d['worst_ori_rad']:.2e} rad"
              f"  nullity {d['nullity']}  limit_viol {d['limit_violations']}")
    print("PASS | worst", f"{out['worst_residual']:.3e}")
