"""Read-only review of fixed-graph save/cold-view separation; no CAD execution."""
from pathlib import Path
import ast, datetime, hashlib, json, re
C=Path(__file__).resolve().parents[1]
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
driver=C/'tools/native_delta_driver.py'; delivery=C/'tools/native_delta_delivery.py'
enum=Path('C:/Users/stude/AppData/Local/Temp/gen_py/3.13/4687F359-55D0-4CD3-B6CF-2EB42C11F989x0x32x0.py')
ds=driver.read_text(encoding='utf-8-sig');vs=delivery.read_text(encoding='utf-8-sig');es=enum.read_text(encoding='utf-8-sig')
ast.parse(ds);ast.parse(vs)
checks={
 'local_enum_AvoidRebuild8':bool(re.search(r'swSaveAsOptions_AvoidRebuildOnSave\s*=\s*8\b',es)),
 'local_enum_Silent1':bool(re.search(r'swSaveAsOptions_Silent\s*=\s*1\b',es)),
 'local_enum_ReadOnly2':bool(re.search(r'swOpenDocOptions_ReadOnly\s*=\s*2\b',es)),
 'save_options9':"ext.SaveAs(str(target),0,9,None,0,0)" in ds,
 'no_force_rebuild_call_in_driver':not re.search(r'\.(?:EditRebuild3|ForceRebuild3)\s*\(',ds),
 'pre_and_post_NeedsRebuild_SaveFlag_records':all(s in ds for s in ["r['pre_save_state']","r['post_save_state']","needs_rebuild2=int(ext.NeedsRebuild2)","save_flag=bool(m.val(model,'GetSaveFlag'))"]),
 'save_requires_nonempty_file_errors0':"target.stat().st_size>0" in ds and "result[1]==0" in ds,
 'close_saved_before_restore_graphics':"b.close_own_saved(model,target,saved['sha256']);r['closed_before_restoring_graphics']=True" in ds,
 'frozen_part_expected_SHA_preserved':"q['native_sha256']=expected_part['native_sha256']" in ds and "q['native_sha256']=m.sha(q['native_path'])" not in ds,
 'assembly_save_SHA_binding_preserved':"digest=assembly_receipt['native_save']['sha256'];assert m.sha(target)==digest" in ds,
 '873_identity_and_cold_metadata_preserved':"b.identity_inventory(asm,rows)" in ds and "lookup,observed=b.metadata(model,rows,False)" in ds,
 'local_dependency_checks_preserved':"assert {m.normalized(p) for p in paths}=={m.normalized(q['native_path']) for q in rows}" in ds and "is_relative_to(folder.resolve())" in ds,
 'readonly_cold195':"sw.OpenDoc6(str(target),2,195" in ds,
 'cold_capture_saved_nativeSHA':"native_sha256=digest,view='ACTUAL_COLD_NATIVE_ISOMETRIC_FIT_NO_FORCE_REBUILD'" in ds,
 'delivery_consumes_cold_capture_bound_to_save':"capture = cold[\"native_view_capture\"]" in vs and "capture.get(\"native_sha256\") == integration[\"native_save\"][\"sha256\"]" in vs,
 'readonly_dirty_view_closes_own_target':"Path(m.val(model,'GetPathName')).resolve()==target.resolve()" in ds and "own_readonly_view_only_change_discarded" in ds,
 'relocation_original_absence_preserved':"not D.exists()" in ds and "original_root_absent_during_cold_open" in ds,
}
assert all(checks.values()),[k for k,v in checks.items() if not v]
hist=C/'results/NATIVE_DELTA_INTEGRATE_V1_ARCHIVE.json';history=json.loads(hist.read_text(encoding='utf-8'))
for f in history:assert sha(f['destination']).casefold()==f['sha256'].casefold() and Path(f['destination']).stat().st_size==f['bytes']
out={'schema':'NATIVE_SAVE_VIEW_SEPARATION_READONLY_REVIEW_V1','reviewed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),
 'status':'PASS_SOURCE_REVIEW_BOUNDED_FIXED_COMPONENT_GRAPH_SAVE__RUNTIME_PENDING','blocking_findings':[],
 'checks_passed':sum(checks.values()),'checks_total':len(checks),'checks':checks,
 'enum_authority':{'path':str(enum),'sha256':sha(enum),'type_library':'SOLIDWORKS2024 swconst.tlb major32 minor0 generated by makepy; reviewed as text, not imported','AvoidRebuildOnSave':8,'Silent':1,'options_or_value':9,'ReadOnly':2,'cold_open_mask':195,'official_reference':'https://help.solidworks.com/2024/English/api/swconst/SOLIDWORKS.Interop.swconst~SOLIDWORKS.Interop.swconst.swSaveAsOptions_e.html'},
 'reviewed_source_sha256':{str(driver):sha(driver),str(delivery):sha(delivery),str(hist):sha(hist)},
 'failed_save_history_preserved_and_checked':history,
 'evidence_scope':{'fixed_component_graph_save_only':True,'fresh_cold_membership_transform_file_integrity_still_required':True,'feature_rebuild_verified':False,'parametric_or_mate_mechanism_verified':False,'NeedsRebuild2_interpretation':'Raw pre/post/cold code retained; a nonzero state is not reclassified as completed feature rebuild. Full fixed graph acceptance requires subsequent cold evidence.','read_only_view_interpretation':'Saved assembly SHA is checked before/after capture; dirty view-only state is discarded on the owned document. Full assembly/part SHA checks remain required for delivery.'},
 'nonblocking_followup':[{'id':'SAVE-VIEW-01','request':'Record BMP SHA256/bytes at successful SaveBMP and compare that hash during delivery, to bind pixel artifact at acquisition instead of only its later path.','source_fix_present_at_review':"bmp.stat().st_size" in ds and "sha256=m.sha(bmp)" in ds}],
 'CAD_COM_OCC_executed_by_reviewer':False,'actual_save_or_cold_success_claimed':False,'manufacturing_release':False}
(C/'review/NATIVE_SAVE_VIEW_REVIEW.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({k:out[k] for k in ['status','checks_passed','checks_total','blocking_findings','nonblocking_followup']}))

